# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-24 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20160124_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pic',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
